# Generated by Django 4.2.11 on 2024-09-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("venue_name", models.CharField(max_length=255)),
                ("capacity", models.IntegerField()),
                ("location", models.CharField(max_length=255)),
            ],
        ),
    ]
