# Generated by Django 4.2.11 on 2024-09-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_venue_hourly_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("status", models.CharField(max_length=255)),
            ],
        ),
    ]
