# Generated by Django 4.2.11 on 2024-09-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_alter_booking_status_customuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="customer_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="booking",
            name="customer_number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
