# Generated by Django 4.2.11 on 2024-09-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_booking_customer_name_booking_customer_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="venue_images/"),
        ),
    ]
