# Generated by Django 4.2.11 on 2024-09-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0006_venue_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "pending"),
                    ("approved", "approved"),
                    ("rejected", "rejected"),
                ],
                max_length=255,
            ),
        ),
    ]
