# Generated by Django 4.2.11 on 2024-09-13 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0008_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
