# Generated by Django 4.2.11 on 2024-09-17 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0009_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="venue",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="booking.venue",
            ),
            preserve_default=False,
        ),
    ]
